import turtle
turtle.bgcolor('purple')
turtle.shape('circle')
turtle.pensize(5)
finn=turtle.clone()
finn.color('green')
finn.pensize(8)
turtle.color('yellow')
finn.shape('triangle')
finn.left(90)
finn.goto(0,-150)
finn.goto(75,-150)
finn.color('blue')
finn.goto(75,0)
turtle.goto(0,150)
turtle.goto(-75,150)
turtle.color('white')
turtle.goto(-75,0)
charlie.clearstamps()
turtle.mainloop()


#square:
#finn=turtle.clone()
#finn.shape('square')
#finn.goto(0,100)
#finn.goto(100,100)
#finn.goto(100,0)
#finn.goto(0,0)

#triangle + stamps:
#charlie=turtle.clone()
#charlie.shape('triangle')
#charlie.goto(200,0)
#charlie.stamp()
#charlie.goto(0,200)
#charlie.stamp()
#charlie.goto(0,0)
#charlie.stamp()
